### ISSUE TITLE
panic: bam: magic number mismatch

### ISSUE THREAD

**Issue by snashraf** [brentp/goleft#24]
Hi I am getting this error while running indexCov with a folder of BAM files. Is their a way to find out that which BAM has a problem? 

goleft indexcov --directory indexCovQGP/ indexQGP/*.bam
panic: bam: magic number mismatch

goroutine 12 [running]:
github.com/brentp/goleft/indexcov.readIndex(0x7fff6666d84a, 0x27, 0x129, 0xc454a61101, 0xc45995ab20, 0x12, 0x125)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:313 +0x2d5
github.com/brentp/goleft/indexcov.Main.func1(0xc420032840, 0xc4202e8000, 0xcef, 0xcef, 0xc42017f500, 0xcef, 0xcef, 0xc420213c10)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:270 +0xaa
created by github.com/brentp/goleft/indexcov.Main
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:275 +0x5e4

**Comment by shenwei356** [comment]
It said

    indexQGP/0100004781_S2_L002.sorted.bam.bai: no such file or directory

That means, you should create index for the bam file using `samtools index`.

**Comment by snashraf** [comment]
Sorry for mistake last time. I have updated question again.

**Comment by brentp** [comment]
It would be nice if this were a better message, but an incorrectly formatted bam is a `panic`. Can you make sure to update to the latest goleft? The problem will likely perisist, but it would be good to verify.

I would first try running `ls -lhS` on your bams and see if any are very small or outliers. If that fails, you can run it on half your samples at a time--doing a binary search to find the problematic bam or bai.

**Comment by brentp** [comment]
I am closing this for lack of activity. please reopen if you can help narrow it down or recreate.
