### ISSUE TITLE
indexcov Unable to run on contigs without a sex chr

### ISSUE THREAD

**Issue by mahesh-panchal** [brentp/goleft#40]
Hi,

I wanted to test indexcov on a sample I have, but it seems this tool does not function without a sex chromosome present. It wasn't clear in the documentation that sex chromosomes need to be present for the tool to function, and it's also not clear how to provide an argument to the --sex parameter.

```
$ goleft_linux64_v0.1.18 indexcov --directory VirusA_results VirusA_bwa_alignment.bam
2018/03/27 10:48:12 indexcov: running on 1 indexes
(WARNING) indexcov: expected 2 sex chromosomes, found: 0.
you can set the expected with --sex ''
2018/03/27 10:48:12 sex chromosomes not found.
2018/03/27 10:48:12 got: 0 principal components
2018/03/27 10:48:12 indexcov: 0 principal components, not plotting
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8fe719]

goroutine 1 [running]:
github.com/brentp/goleft/indexcov.plotBins(0xc42000c148, 0x1, 0x1, 0xc4200672f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/plot.go:194 +0x5c9
github.com/brentp/goleft/indexcov.writeIndex(0xc420075e60, 0xc42000c148, 0x1, 0x1, 0xc4200f06c0, 0x2, 0x2, 0xc4200672f0, 0x1, 0x1, ...)
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:697 +0x2b1
github.com/brentp/goleft/indexcov.Main()
	/home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:396 +0x82f
main.main()
	/home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:68 +0x17f
```
```
$ goleft_linux64_v0.1.18 indexcov --sex 0 --directory VirusA_results VirusA_bwa_alignment.bam
2018/03/27 10:48:30 indexcov: running on 1 indexes
2018/03/27 10:48:30 (FATAL) indexcov: expected 1 sex chromosomes, found: 0.
you can set the expected with --sex ''
```
```
$ goleft_linux64_v0.1.18 indexcov --sex false --directory VirusA_results VirusA_bwa_alignment.bam
2018/03/27 10:49:07 indexcov: running on 1 indexes
2018/03/27 10:49:07 (FATAL) indexcov: expected 1 sex chromosomes, found: 0.
you can set the expected with --sex ''
```

Regards,
Mahesh.

**Comment by brentp** [comment]
as the error message is indicating you need to run as:
 `--sex '' --directory VirusA_results`
you are running as:
 `--sex --directory VirusA_results`

**Comment by mahesh-panchal** [comment]
Ah, ok. I understand now. Thank you for your quick response.
