### ISSUE TITLE
indexsplit for 2000 samples fail

### ISSUE THREAD

**Issue by veeravalli** [brentp/goleft#47]
Hi, I am trying to run indexsplit for around 2000 samples with cram indices as input 
Commandline works perfectly fine for 10 samples. Even for 20 samples, I get the following error.
Is there a limitation for number of samples? Thanks.

`goleft indexsplit --n 5000 --fai Homo_sapiens_assembly38.fasta.fai  1.crai   2.crai  3.crai.......2000.crai`

`panic: runtime error: index out of range

goroutine 19 [running]:
github.com/brentp/goleft/indexsplit.Split.func1(0xc4201c2200, 0x14, 0x20, 0xc4203aa000, 0xd26, 0xd26, 0xc4201c4060, 0x1388, 0x0)
        /home/brentp/go/src/github.com/brentp/goleft/indexsplit/indexsplit.go:101 +0x1058
created by github.com/brentp/goleft/indexsplit.Split
        /home/brentp/go/src/github.com/brentp/goleft/indexsplit/indexsplit.go:84 +0xc3
`
Regards

**Comment by brentp** [comment]
can you try the latest version of goleft? your line numbers don't match mine and I have no changes since last release.
But, I suspect you have an odd crai in there somewhere. maybe you could do a sort of binary search, running on half, repeating on the half that fails and so on until you find the crai that's causing the problem. If you could share that, I could debug further

**Comment by veeravalli** [comment]
Thanks. I downloaded the latest binary (goleft Version: 0.1.18) and tried. 
I managed to find a problematic cram index and sent you by email.

Please find the commandline as below. I downloaded the latest version.

goleft_linux64 indexsplit --n 5000 --fai   Homo_sapiens_assembly38.fasta.fai   WHH2408.bqsr.cram.crai > test.bed 
panic: runtime error: index out of range

goroutine 75 [running]:
github.com/brentp/goleft/indexsplit.Split.func1(0xc4201da5a0, 0x1, 0x1, 0xc420442000, 0xd26, 0xd26, 0xc4200f6240, 0x1388, 0x0)
        /home/brentp/go/src/github.com/brentp/goleft/indexsplit/indexsplit.go:102 +0x101a
created by github.com/brentp/goleft/indexsplit.Split
        /home/brentp/go/src/github.com/brentp/goleft/indexsplit/indexsplit.go:85 +0xc3

Have used samtools 1.8 to index the cram file.
